#newlines switch the speaker
lore = (
    "<click to advance the lore>\n"
    "Why does boss want so much info on random planets..?\n"
    "Yeah man...This mission seems pointless. We already scanned 2.3e+15 planets yesterday, including rogue ones... What could he possibly do with all that data?\n"
    "Well, atleast we can scan efficently. Remember yesterday? We scanned at 8e+10 planets per second!\n"
    "That's true. I heard some cilivizations actually need get in orbit to get the planet's data!\n"
    "Seriously?? I remember a few years ago we only had a range of a light-year, even that was terrible. "
    "I can't imagine such primitive technology!\n"
    "Yeah, if you had to orbit each planet, you couldn't travel 200x light speed!\n"
    "I bet their technology is so bad that they have to stay in orbit for a minute or so just to scan one planet.\n"
    "Really now? Then they could only get hundreds of planets a day then.\n"
    "Boss won't even consider a number without scientific notation nowadays...\n"
    "Yeah, atleast we're advanced... Anyway, lets get the day started. Turn on the planet scanner.\n"
    "*Flips Switch* Hey! The terminal is reading SyntaxError: invalid syntax on line 5432: print(hello world)\n"
    "??? What do you mean, shouldn't the console print 'hello world'?\n"
    "No, dingus. Theres no quotes. No wonder you failed programming 101...\n"
    "Since your soooo smart, why don't you fix the error?\n"
    "We don't have access to the source code of this ship...\n"
    "What does that mean\n"
    "I can't fix the error, we can't scan planets.\n"
    "ARE YOU SERIOUS!!! We are 12 TRILLION univerises away from home, and NOW you tell me that?\n"
    "Not my fault man. We'll be fine though. I just remembered that I have this wireless barcode scanner from work "
    "that I accidently took from my shift. It only has a range of several hundred km though, so we'll have to "
    "go orbit planets for a minute or so to scan them\n"
    "Uhm, excuse me? That sounds just like that primitive technology! I am NOT having it!\n"
    "Boss will kill us if we return home with no planet data...\n"
    "But.. A barcode scanner? To scan a planet? Thats INSANE!\n"
    "We'll have to make do with...... The Wrong Tool for the Job\n"
    "<end>"
)
